// Generated by CoffeeScript 2.5.1
var sendCoffee;

import {
  Client
} from "discord.js";

console.log("coffee yeet, yeet coffee");

sendCoffee = async(channel, coffeeString, msDelay = 5000) => {
  var coffeeMsg;
  coffeeString = "Coffee: " + coffeeString;
  coffeeMsg = (await channel.send(coffeeString).catch(() => {
    return Promise.resolve();
  }));
  if (coffeeMsg) {
    coffeeMsg.delete({
      timeout: msDelay
    });
  }
  return Promise.resolve(coffeeMsg);
};

export {
  sendCoffee
};
